name: Capturar Screenshots

on:
  schedule:
    - cron: '*/2 * * * *' # de 2 em 2 minutos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositÃ³rio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependÃªncias
        run: npm install

      - name: Executar captura
        run: npm start

      - name: Fazer commit das imagens
        run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git pull --rebase
        git add img/
        git commit -m 'ðŸ“¸ Atualizar screenshots automÃ¡ticas' || echo 'Sem alteraÃ§Ãµes'
        git push
